ALTER TABLE recharge_plan
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'admin';

ALTER TABLE recharge_campaign
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'admin',
  ADD COLUMN IF NOT EXISTS operator VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS operation_reason VARCHAR(255) NOT NULL DEFAULT '';
